perms = {
    "admin": "ADMINISTRATOR",
    "kick": "KICK_MEMBERS",
    "ban": "BAN_MEMBERS",
    "manageserver": "MANAGE_GUILD",
    "managemessages": "MANAGE_MESSAGES",
    "managenicknames": "MANAGE_NICKNAMES",
    "viewauditlogs": "VIEW_AUDIT_LOG",
    "viewinsights": "VIEW_GUILD_INSIGHTS",
    "manageroles": "MANAGE_ROLES",
    "managechannels": "MANAGE_CHANNELS",
    "manageemojis": "MANAGE_EMOJIS",
    "managewebhooks": "MANAGE_WEBHOOKS",
    "createinvite": "CREATE_INSTANT_INVITE",
    "sendmessages": "SEND_MESSAGES",
    "sendtts": "SEND_TTS_MESSAGES",
    "readhistory": "READ_MESSAGE_HISTORY",
    "viewchannels": "VIEW_CHANNEL",
    "attachfiles": "ATTACH_FILES",
    "embedlinks": "EMBED_LINKS",
    "changenickname": "CHANGE_NICKNAME",
    "addreactions": "ADD_REACTIONS",
    "externalemojis": "USE_EXTERNAL_EMOJIS",
    "mentioneveryone": "MENTION_EVERYONE",
    "priorityspeaker": "PRIORITY_SPEAKER",
    "video": "STREAM",
    "connect": "CONNECT",
    "speak": "SPEAK",
    "mutemembers": "MUTE_MEMBERS",
    "deafenmembers": "DEAFEN_MEMBERS",
    "movemembers": "MOVE_MEMBERS"

}